// This file is auto-generated by @hey-api/openapi-ts

export const UserDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        createdAt: {
            type: 'string'
        }
    },
    required: [
        'id',
        'email',
        'createdAt'
    ]
} as const;

export const SongDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        ownerId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        artist: {
            type: 'string'
        },
        album: {
            type: 'string'
        },
        duration: {
            type: 'number'
        },
        hasCover: {
            type: 'boolean'
        },
        addedAt: {
            type: 'string'
        }
    },
    required: [
        'id',
        'ownerId',
        'title',
        'duration',
        'hasCover',
        'addedAt'
    ]
} as const;

export const UpdateSongDtoSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            minLength: 1
        },
        artist: {
            type: 'string'
        },
        album: {
            type: 'string'
        }
    },
    required: [
        'title'
    ]
} as const;

export const PlaylistEntryDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        songId: {
            type: 'string'
        },
        position: {
            type: 'number'
        }
    },
    required: [
        'id',
        'songId',
        'position'
    ]
} as const;

export const PlaylistDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        ownerId: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        entries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PlaylistEntryDto'
            }
        },
        trackCount: {
            type: 'number'
        },
        createdAt: {
            type: 'string',
            description: 'When the playlist was created, as an ISO 8601 timestamp.'
        }
    },
    required: [
        'id',
        'ownerId',
        'name',
        'entries',
        'trackCount',
        'createdAt'
    ]
} as const;

export const CreatePlaylistDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1
        }
    },
    required: [
        'name'
    ]
} as const;

export const RenamePlaylistDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1
        }
    },
    required: [
        'name'
    ]
} as const;

export const AddEntryDtoSchema = {
    type: 'object',
    properties: {
        songId: {
            type: 'string',
            format: 'uuid'
        }
    },
    required: [
        'songId'
    ]
} as const;

export const ReorderEntriesDtoSchema = {
    type: 'object',
    properties: {
        entryIds: {
            minItems: 1,
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    },
    required: [
        'entryIds'
    ]
} as const;
