// This file is auto-generated by @hey-api/openapi-ts

export const UserDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        }
    },
    required: [
        'id',
        'name',
        'email'
    ]
} as const;

export const UpdateUserDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1
        },
        email: {
            type: 'string',
            format: 'email'
        }
    },
    required: [
        'name',
        'email'
    ]
} as const;
