// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { UsersControllerGetUserData, UsersControllerGetUserResponses, UsersControllerReplaceUserData, UsersControllerReplaceUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * The current user.
 */
export const usersControllerGetUser = <ThrowOnError extends boolean = false>(options?: Options<UsersControllerGetUserData, ThrowOnError>): RequestResult<UsersControllerGetUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<UsersControllerGetUserResponses, unknown, ThrowOnError>({ url: '/user', ...options });

/**
 * Replace the current user and return the stored record.
 */
export const usersControllerReplaceUser = <ThrowOnError extends boolean = false>(options: Options<UsersControllerReplaceUserData, ThrowOnError>): RequestResult<UsersControllerReplaceUserResponses, unknown, ThrowOnError> => (options.client ?? client).put<UsersControllerReplaceUserResponses, unknown, ThrowOnError>({
    url: '/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
