// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AuthControllerMeData, AuthControllerMeResponses, AuthControllerRegisterData, AuthControllerRegisterResponses, AuthControllerSignInData, AuthControllerSignInResponses, AuthControllerSignOutData, AuthControllerSignOutResponses, PlaylistsControllerAddEntryData, PlaylistsControllerAddEntryResponses, PlaylistsControllerCreateData, PlaylistsControllerCreateResponses, PlaylistsControllerGetData, PlaylistsControllerGetResponses, PlaylistsControllerListData, PlaylistsControllerListResponses, PlaylistsControllerRemoveData, PlaylistsControllerRemoveEntryData, PlaylistsControllerRemoveEntryResponses, PlaylistsControllerRemoveResponses, PlaylistsControllerRenameData, PlaylistsControllerRenameResponses, PlaylistsControllerReorderData, PlaylistsControllerReorderResponses, SongsControllerAudioData, SongsControllerAudioResponses, SongsControllerCoverData, SongsControllerCoverResponses, SongsControllerGetData, SongsControllerGetResponses, SongsControllerListData, SongsControllerListResponses, SongsControllerRemoveData, SongsControllerRemoveResponses, SongsControllerRetagData, SongsControllerRetagResponses, SongsControllerUploadData, SongsControllerUploadResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const authControllerRegister = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRegisterData, ThrowOnError>): RequestResult<AuthControllerRegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthControllerRegisterResponses, unknown, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerSignIn = <ThrowOnError extends boolean = false>(options: Options<AuthControllerSignInData, ThrowOnError>): RequestResult<AuthControllerSignInResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthControllerSignInResponses, unknown, ThrowOnError>({
    url: '/auth/sign-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerSignOut = <ThrowOnError extends boolean = false>(options: Options<AuthControllerSignOutData, ThrowOnError>): RequestResult<AuthControllerSignOutResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthControllerSignOutResponses, unknown, ThrowOnError>({ url: '/auth/sign-out', ...options });

export const authControllerMe = <ThrowOnError extends boolean = false>(options: Options<AuthControllerMeData, ThrowOnError>): RequestResult<AuthControllerMeResponses, unknown, ThrowOnError> => (options.client ?? client).get<AuthControllerMeResponses, unknown, ThrowOnError>({ url: '/auth/me', ...options });

export const songsControllerList = <ThrowOnError extends boolean = false>(options?: Options<SongsControllerListData, ThrowOnError>): RequestResult<SongsControllerListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SongsControllerListResponses, unknown, ThrowOnError>({ url: '/songs', ...options });

/**
 * Upload an .mp3. Metadata comes from the file's ID3 tags; edit later via PATCH.
 */
export const songsControllerUpload = <ThrowOnError extends boolean = false>(options: Options<SongsControllerUploadData, ThrowOnError>): RequestResult<SongsControllerUploadResponses, unknown, ThrowOnError> => (options.client ?? client).post<SongsControllerUploadResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/songs',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const songsControllerRemove = <ThrowOnError extends boolean = false>(options: Options<SongsControllerRemoveData, ThrowOnError>): RequestResult<SongsControllerRemoveResponses, unknown, ThrowOnError> => (options.client ?? client).delete<SongsControllerRemoveResponses, unknown, ThrowOnError>({ url: '/songs/{id}', ...options });

export const songsControllerGet = <ThrowOnError extends boolean = false>(options: Options<SongsControllerGetData, ThrowOnError>): RequestResult<SongsControllerGetResponses, unknown, ThrowOnError> => (options.client ?? client).get<SongsControllerGetResponses, unknown, ThrowOnError>({ url: '/songs/{id}', ...options });

export const songsControllerRetag = <ThrowOnError extends boolean = false>(options: Options<SongsControllerRetagData, ThrowOnError>): RequestResult<SongsControllerRetagResponses, unknown, ThrowOnError> => (options.client ?? client).patch<SongsControllerRetagResponses, unknown, ThrowOnError>({
    url: '/songs/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Audio bytes with HTTP Range support — `206` when a range is asked for (SNG-2, PB-1).
 */
export const songsControllerAudio = <ThrowOnError extends boolean = false>(options: Options<SongsControllerAudioData, ThrowOnError>): RequestResult<SongsControllerAudioResponses, unknown, ThrowOnError> => (options.client ?? client).get<SongsControllerAudioResponses, unknown, ThrowOnError>({ url: '/songs/{id}/audio', ...options });

/**
 * Cover image. Small and immutable for a given song, so cache it hard.
 */
export const songsControllerCover = <ThrowOnError extends boolean = false>(options: Options<SongsControllerCoverData, ThrowOnError>): RequestResult<SongsControllerCoverResponses, unknown, ThrowOnError> => (options.client ?? client).get<SongsControllerCoverResponses, unknown, ThrowOnError>({ url: '/songs/{id}/cover', ...options });

export const playlistsControllerList = <ThrowOnError extends boolean = false>(options?: Options<PlaylistsControllerListData, ThrowOnError>): RequestResult<PlaylistsControllerListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PlaylistsControllerListResponses, unknown, ThrowOnError>({ url: '/playlists', ...options });

export const playlistsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<PlaylistsControllerCreateData, ThrowOnError>): RequestResult<PlaylistsControllerCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<PlaylistsControllerCreateResponses, unknown, ThrowOnError>({
    url: '/playlists',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const playlistsControllerRemove = <ThrowOnError extends boolean = false>(options: Options<PlaylistsControllerRemoveData, ThrowOnError>): RequestResult<PlaylistsControllerRemoveResponses, unknown, ThrowOnError> => (options.client ?? client).delete<PlaylistsControllerRemoveResponses, unknown, ThrowOnError>({ url: '/playlists/{id}', ...options });

export const playlistsControllerGet = <ThrowOnError extends boolean = false>(options: Options<PlaylistsControllerGetData, ThrowOnError>): RequestResult<PlaylistsControllerGetResponses, unknown, ThrowOnError> => (options.client ?? client).get<PlaylistsControllerGetResponses, unknown, ThrowOnError>({ url: '/playlists/{id}', ...options });

export const playlistsControllerRename = <ThrowOnError extends boolean = false>(options: Options<PlaylistsControllerRenameData, ThrowOnError>): RequestResult<PlaylistsControllerRenameResponses, unknown, ThrowOnError> => (options.client ?? client).patch<PlaylistsControllerRenameResponses, unknown, ThrowOnError>({
    url: '/playlists/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const playlistsControllerAddEntry = <ThrowOnError extends boolean = false>(options: Options<PlaylistsControllerAddEntryData, ThrowOnError>): RequestResult<PlaylistsControllerAddEntryResponses, unknown, ThrowOnError> => (options.client ?? client).post<PlaylistsControllerAddEntryResponses, unknown, ThrowOnError>({
    url: '/playlists/{id}/entries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const playlistsControllerReorder = <ThrowOnError extends boolean = false>(options: Options<PlaylistsControllerReorderData, ThrowOnError>): RequestResult<PlaylistsControllerReorderResponses, unknown, ThrowOnError> => (options.client ?? client).put<PlaylistsControllerReorderResponses, unknown, ThrowOnError>({
    url: '/playlists/{id}/entries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const playlistsControllerRemoveEntry = <ThrowOnError extends boolean = false>(options: Options<PlaylistsControllerRemoveEntryData, ThrowOnError>): RequestResult<PlaylistsControllerRemoveEntryResponses, unknown, ThrowOnError> => (options.client ?? client).delete<PlaylistsControllerRemoveEntryResponses, unknown, ThrowOnError>({ url: '/playlists/{id}/entries/{entryId}', ...options });
