// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type UserDto = {
    id: string;
    name: string;
    email: string;
};

export type UpdateUserDto = {
    name: string;
    email: string;
};

export type UsersControllerGetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type UsersControllerGetUserResponses = {
    200: UserDto;
};

export type UsersControllerGetUserResponse = UsersControllerGetUserResponses[keyof UsersControllerGetUserResponses];

export type UsersControllerReplaceUserData = {
    body: UpdateUserDto;
    path?: never;
    query?: never;
    url: '/user';
};

export type UsersControllerReplaceUserResponses = {
    200: UserDto;
};

export type UsersControllerReplaceUserResponse = UsersControllerReplaceUserResponses[keyof UsersControllerReplaceUserResponses];
