// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from '@tanstack/angular-query-experimental';

import { client } from '../client.gen';
import { type Options, usersControllerGetUser, usersControllerReplaceUser } from '../sdk.gen';
import type { UsersControllerGetUserData, UsersControllerGetUserResponse, UsersControllerReplaceUserData, UsersControllerReplaceUserResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const usersControllerGetUserQueryKey = (options?: Options<UsersControllerGetUserData>) => createQueryKey('usersControllerGetUser', options);

/**
 * The current user.
 */
export const usersControllerGetUserOptions = (options?: Options<UsersControllerGetUserData>) => queryOptions<UsersControllerGetUserResponse, DefaultError, UsersControllerGetUserResponse, ReturnType<typeof usersControllerGetUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await usersControllerGetUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: usersControllerGetUserQueryKey(options)
});

/**
 * Replace the current user and return the stored record.
 */
export const usersControllerReplaceUserMutation = (options?: Partial<Options<UsersControllerReplaceUserData>>): MutationOptions<UsersControllerReplaceUserResponse, DefaultError, Options<UsersControllerReplaceUserData>> => {
    const mutationOptions: MutationOptions<UsersControllerReplaceUserResponse, DefaultError, Options<UsersControllerReplaceUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await usersControllerReplaceUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
